[build]
builder = "nixpacks"

[deploy]
startCommand = "python railway_app.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[environment]
PYTHONPATH = "."
PORT = "$PORT"
